version: '3'
services:
        dev:
                image: node:14
                volumes:
                        - nodemodules:/usr/src/merng_app/node_modules
                        - .:/usr/src/merng_app
                environment:
                        - NODE_ENV=development
                working_dir: /usr/src/merng_app
                command: bash
volumes:
        nodemodules:
                external: true
